### ISSUE TITLE
AddVisNetwork doesn't work on Blazor server websites

### ISSUE THREAD

**Issue by jbgh2** [stiankroknes/VisNetwork.Blazor#20]
`AddVisNetwork` adds a singleton `IJsModule` which has a dependency on `IJsRuntime` therefore requiring that `IJsRuntime` also be a singleton

On Blazor server `IJsRuntime` is scoped (see https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-7.0#default-services)

Current workaround:
1. Create a new class that derives from `IVersionProvider`
    - This step is required because `VersionProvider` is `internal` not `public`
3. Add the services manually

Suggestions:
1. Create a version of `AddVisNetwork` for scoped used 
4. Make `VersionProvider` public, this makes it easier to build the equivalent to `AddVisNetwork`

**Comment by oalt** [comment]
I have the same problem. Try adding a second configuration method helps (in VisNetworkConfiguration.cs):

public static IServiceCollection AddVisNetworkServer(this IServiceCollection services)
    {
        services.AddSingleton<IVersionProvider, VersionProvider>();
        services.AddScoped<IJSModule, JSModule>();
        return services;
    }

**Comment by stiankroknes** [comment]
Thanks for reporting the issue. Should be fixed in 1.0.1 release.
