### ISSUE TITLE
Destroying VisNetwork

### ISSUE THREAD

**Issue by mloutsaris** [stiankroknes/VisNetwork.Blazor#31]
Hello, 

thanks you for work. I would like to ask you how can i destroy the visnetwork. Actually, i have a modal that includes the Network and when i close it, the console have the following error 
```
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'id')
TypeError: Cannot read properties of null (reading 'id')
    at Module.hR (https://localhost:7114/_content/VisNetwork.Blazor/BlazorVisNetwork.js?v=2.0.0.0:2:697560)
    at https://localhost:7114/_framework/blazor.webassembly.js:1:3332
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:7114/_framework/blazor.webassembly.js:1:3306)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7114/_framework/blazor.webassembly.js:1:59960)
    at _mono_wasm_invoke_js_blazor (https://localhost:7114/_framework/dotnet.6.0.15.33m2xdwuzc.js:1:195300)
    at wasm://wasm/00971dfa:wasm-function[219]:0x1a4c1
    at wasm://wasm/00971dfa:wasm-function[167]:0xce8f
    at wasm://wasm/00971dfa:wasm-function[166]:0xbd73
    at wasm://wasm/00971dfa:wasm-function[2815]:0xabef3
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at VisNetwork.Blazor.JSModule.InvokeVoidAsync(String identifier, Object[] args)
   at VisNetwork.Blazor.Network.System.IAsyncDisposable.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<ProcessDisposalQueueInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|64_0(Task result)
```

I assume that is searching for the Id when the StateHasChanged (the modal has changed).

Can you tell me if there is any way to solve this error ?

Thank you in advance.

**Comment by stiankroknes** [comment]
Hello, sorry for the delay. I tried to reproduce using https://blazored.github.io/Modal/ but did not get any errors.
Can you provide a simple example/repo? 

Did find a missing safe guard in the javascript part of the library. Will fix it soon.

**Comment by mloutsaris** [comment]
Hi, thanks one more time for your time. 

I am using Sklusive UI - https://skclusive.github.io/Skclusive.Material.Docs/modal and an example of how i am using the visnetwork inside this modal is the following: 

`@if (Open)
{
    <Modal aria-labelledby="simple-modal-title" aria-describedby="simple-modal-description" Open="@Open" KeepMounted=true OnClose="@HandleClose"
       OnBackdropClick="@OnBackdropClick"
       OnEscapeKeyDown="@OnEscapeKeyDown">
        <BackdropContent>
            <Backdrop Open="@context.Open"
                  OnClick="@context.OnBackdropClick" />
        </BackdropContent>
        <ChildContent>
            <div style="@ModelStyle" class="simple-modal-paper">
                <Network Id="@LegalDocument.Id" @ref="network" Data="@data" style="width: 100%; height:100%;" />
            </div>
        </ChildContent>
    </Modal>
}`

Also, the modal is openned by clicking the following button:

`<RadzenSplitButtonItem @onclick="HandleOpen" Text="Visualize Correlations" Value="2" />`

which when clicked run the function handleopen. This function builds the network based on the displayed data.
` private void HandleOpen()
    {
        //Network Data
        var nodes = new List<Node>();
        var edges = new List<VisNetwork.Blazor.Models.Edge>();
        //Creating Data for the Network
        nodes.Add(new Node(LegalDocument.docType + " " + LegalDocument.docNumber, LegalDocument.docType + " " + LegalDocument.docNumber, 1, "ellipse"));
        foreach (var currentLDParts in LegalDocument.LawBody)
        {
            nodes.Add(new Node(currentLDParts.BodyId, currentLDParts.BodyId, 1, "ellipse"));
        }
        foreach (var currentLDParts in LegalDocument.LawBody)
        {
            edges.Add(new VisNetwork.Blazor.Models.Edge(LegalDocument.docType + " " + LegalDocument.docNumber, currentLDParts.BodyId));
        }
        foreach (var cor in correlations.GroupBy(c => c.SourceLDNumber).Select(g => g.First()))
        {
            nodes.Add(new Node(cor.SourceLDType + " " + cor.SourceLDNumber, cor.SourceLDType + " " + cor.SourceLDNumber, 1, "ellipse"));
            foreach (var corlevel2 in correlations)
            {
                if (corlevel2.SourceLDId == cor.SourceLDId)
                {
                    nodes.Add(new Node(corlevel2.SourceLDId + " " + corlevel2.SourceLDPartId, corlevel2.SourceLDPartId, 1, "ellipse"));
                    edges.Add(new VisNetwork.Blazor.Models.Edge(cor.SourceLDType + " " + cor.SourceLDNumber, corlevel2.SourceLDId + " " + corlevel2.SourceLDPartId));
                }
            }
        }
        foreach (var currentLDParts in LegalDocument.LawBody)
        {
            foreach (var corlevel2 in correlations)
            {
                if (currentLDParts.BodyId == corlevel2.CorrelationTargetLDPartNumber)
                {
                    edges.Add(new VisNetwork.Blazor.Models.Edge(currentLDParts.BodyId, corlevel2.SourceLDId + " " + corlevel2.SourceLDPartId));
                }
            }

        }`

Thank you for your perfect package.
